//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_Match
    {
        public int id_gamematch { get; set; }
        public string code { get; set; }
        public string language { get; set; }
        public Nullable<int> id_word { get; set; }
        public Nullable<int> id_challenger { get; set; }
        public Nullable<int> id_guesser { get; set; }
        public Nullable<int> id_match_status { get; set; }
        public Nullable<int> id_match_language { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
        public virtual Match_Language Match_Language { get; set; }
        public virtual Match_Status Match_Status { get; set; }
        public virtual Word Word { get; set; }
    }
}
