//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gamematch
    {
        public int idGamematch { get; set; }
        public string code { get; set; }
        public string language { get; set; }
        public Nullable<int> idWord { get; set; }
        public Nullable<int> idChallenger { get; set; }
        public Nullable<int> idGuesser { get; set; }
        public Nullable<int> idMatchStatus { get; set; }
        public Nullable<int> idMatchLanguage { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
        public virtual MatchLanguage MatchLanguage { get; set; }
        public virtual MatchStatus MatchStatus { get; set; }
        public virtual Word Word { get; set; }
    }
}
