//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HangmanDbEntities : DbContext
    {
        public HangmanDbEntities()
            : base("name=HangmanDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Gamematch> Gamematch { get; set; }
        public virtual DbSet<MatchLanguage> MatchLanguage { get; set; }
        public virtual DbSet<MatchStatus> MatchStatus { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<Word> Word { get; set; }
    }
}
