//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Views.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Views.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string btnAccept {
            get {
                return ResourceManager.GetString("btnAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse.
        /// </summary>
        public static string btnAccessCode {
            get {
                return ResourceManager.GetString("btnAccessCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tengo un código.
        /// </summary>
        public static string btnAccessGame {
            get {
                return ResourceManager.GetString("btnAccessGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Animales.
        /// </summary>
        public static string btnAnimals {
            get {
                return ResourceManager.GetString("btnAnimals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ciudades.
        /// </summary>
        public static string btnCities {
            get {
                return ResourceManager.GetString("btnCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        public static string btnCreate {
            get {
                return ResourceManager.GetString("btnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear partida.
        /// </summary>
        public static string btnCreateGame {
            get {
                return ResourceManager.GetString("btnCreateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frutas.
        /// </summary>
        public static string btnFruits {
            get {
                return ResourceManager.GetString("btnFruits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instrumentos.
        /// </summary>
        public static string btnInstruments {
            get {
                return ResourceManager.GetString("btnInstruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse.
        /// </summary>
        public static string btnJoinGame {
            get {
                return ResourceManager.GetString("btnJoinGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar cambios.
        /// </summary>
        public static string btnModify {
            get {
                return ResourceManager.GetString("btnModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocupaciones.
        /// </summary>
        public static string btnOccupations {
            get {
                return ResourceManager.GetString("btnOccupations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string btnOut {
            get {
                return ResourceManager.GetString("btnOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Empezar.
        /// </summary>
        public static string btnStart {
            get {
                return ResourceManager.GetString("btnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver estadísticas.
        /// </summary>
        public static string btnViewStatistics {
            get {
                return ResourceManager.GetString("btnViewStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de acceso.
        /// </summary>
        public static string lbAccessCode {
            get {
                return ResourceManager.GetString("lbAccessCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de la partida.
        /// </summary>
        public static string lbAccessCodeLobby {
            get {
                return ResourceManager.GetString("lbAccessCodeLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verifique el código de acceso, no existe alguna partida con ese código..
        /// </summary>
        public static string lbAccessCodeMessage {
            get {
                return ResourceManager.GetString("lbAccessCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró el código de acceso.
        /// </summary>
        public static string lbAccessCodeNotFound {
            get {
                return ResourceManager.GetString("lbAccessCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de nacimiento.
        /// </summary>
        public static string lbBirthday {
            get {
                return ResourceManager.GetString("lbBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar idioma.
        /// </summary>
        public static string lbChangeLanguage {
            get {
                return ResourceManager.GetString("lbChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear perfil.
        /// </summary>
        public static string lbCreateProfile {
            get {
                return ResourceManager.GetString("lbCreateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato de fecha incorrecto. Por favor, ingresa una fecha en formato dd-MM-yyyy..
        /// </summary>
        public static string lbDateError {
            get {
                return ResourceManager.GetString("lbDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error: el usuario y/o correo ya existen.
        /// </summary>
        public static string lbDateExists {
            get {
                return ResourceManager.GetString("lbDateExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a se ha desconectado de la partida.
        /// </summary>
        public static string lbDisconnectedPlayer {
            get {
                return ResourceManager.GetString("lbDisconnectedPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar perfil.
        /// </summary>
        public static string lbEditProfile {
            get {
                return ResourceManager.GetString("lbEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string lbEmail {
            get {
                return ResourceManager.GetString("lbEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo vacío.
        /// </summary>
        public static string lbEmptyField {
            get {
                return ResourceManager.GetString("lbEmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dato incorrecto.
        /// </summary>
        public static string lbError {
            get {
                return ResourceManager.GetString("lbError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre completo.
        /// </summary>
        public static string lbFullName {
            get {
                return ResourceManager.GetString("lbFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partidas disponibles.
        /// </summary>
        public static string lbItemsGames {
            get {
                return ResourceManager.GetString("lbItemsGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a se ha unido a la partida.
        /// </summary>
        public static string lbJoinPlayer {
            get {
                return ResourceManager.GetString("lbJoinPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alguien se ha unido a la partida.
        /// </summary>
        public static string lbLobby {
            get {
                return ResourceManager.GetString("lbLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sala ya esta completa, busque otra partida.
        /// </summary>
        public static string lbLobbyComplete {
            get {
                return ResourceManager.GetString("lbLobbyComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sala ya esta completa.
        /// </summary>
        public static string lbLobbyIsComplete {
            get {
                return ResourceManager.GetString("lbLobbyIsComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás listo 
        ///para descifrar palabras y salvar al ahorcado?.
        /// </summary>
        public static string lbLoginMessage {
            get {
                return ResourceManager.GetString("lbLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Hola de nuevo,.
        /// </summary>
        public static string lbLoginSucces {
            get {
                return ResourceManager.GetString("lbLoginSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Oh no han adivinado la palabra!.
        /// </summary>
        public static string lbLose {
            get {
                return ResourceManager.GetString("lbLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido conectar con el servidor, inténtelo más tarde..
        /// </summary>
        public static string lbMessageErrorServer {
            get {
                return ResourceManager.GetString("lbMessageErrorServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario se ha desconectado, la partida ha sido cancelada..
        /// </summary>
        public static string lbMessageGameCanceled {
            get {
                return ResourceManager.GetString("lbMessageGameCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡No han adivinado la palabra correctamente!.
        /// </summary>
        public static string lbMessageWinChallenger {
            get {
                return ResourceManager.GetString("lbMessageWinChallenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Adivinaste la palabra correcta!.
        /// </summary>
        public static string lbMessageWinningGuesser {
            get {
                return ResourceManager.GetString("lbMessageWinningGuesser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha modificado correctamente el perfil.
        /// </summary>
        public static string lbModifySuccess {
            get {
                return ResourceManager.GetString("lbModifySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string lbPassword {
            get {
                return ResourceManager.GetString("lbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirma contraseña .
        /// </summary>
        public static string lbPasswordConfirm {
            get {
                return ResourceManager.GetString("lbPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden..
        /// </summary>
        public static string lbPasswordDontMatch {
            get {
                return ResourceManager.GetString("lbPasswordDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El campo de contraseña no debe estar vacío..
        /// </summary>
        public static string lbPasswordEmpty {
            get {
                return ResourceManager.GetString("lbPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string lbPhone {
            get {
                return ResourceManager.GetString("lbPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido.
        /// </summary>
        public static string lbPlayerGreeting {
            get {
                return ResourceManager.GetString("lbPlayerGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos.
        /// </summary>
        public static string lbPoints {
            get {
                return ResourceManager.GetString("lbPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tienes perfil aún? ¡Regístrate aquí!.
        /// </summary>
        public static string lbRegister {
            get {
                return ResourceManager.GetString("lbRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha creado correctamente el perfil.
        /// </summary>
        public static string lbRegisterSuccess {
            get {
                return ResourceManager.GetString("lbRegisterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string lbSignOut {
            get {
                return ResourceManager.GetString("lbSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estadísticas.
        /// </summary>
        public static string lbStadistics {
            get {
                return ResourceManager.GetString("lbStadistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lbStadisticsMenu {
            get {
                return ResourceManager.GetString("lbStadisticsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registar jugador.
        /// </summary>
        public static string lbTitle {
            get {
                return ResourceManager.GetString("lbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de acceso.
        /// </summary>
        public static string lbTitleAccesssCode {
            get {
                return ResourceManager.GetString("lbTitleAccesssCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error.
        /// </summary>
        public static string lbTitleError {
            get {
                return ResourceManager.GetString("lbTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Credenciales incorrectas.
        /// </summary>
        public static string lbTitleErrorCredentials {
            get {
                return ResourceManager.GetString("lbTitleErrorCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión.
        /// </summary>
        public static string lbTitleErrorServer {
            get {
                return ResourceManager.GetString("lbTitleErrorServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos ya existentes.
        /// </summary>
        public static string lbTitleExistsDate {
            get {
                return ResourceManager.GetString("lbTitleExistsDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar idioma.
        /// </summary>
        public static string lbTitleIdiom {
            get {
                return ResourceManager.GetString("lbTitleIdiom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string lbTitleLogin {
            get {
                return ResourceManager.GetString("lbTitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Oh no! ¡Haz sido ahorcado!.
        /// </summary>
        public static string lbTitleLosser {
            get {
                return ResourceManager.GetString("lbTitleLosser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar.
        /// </summary>
        public static string lbTitleModify {
            get {
                return ResourceManager.GetString("lbTitleModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificación exitosa.
        /// </summary>
        public static string lbTitleModifySuccess {
            get {
                return ResourceManager.GetString("lbTitleModifySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registroso exitoso.
        /// </summary>
        public static string lbTitleRegisterSucces {
            get {
                return ResourceManager.GetString("lbTitleRegisterSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campos vacíos.
        /// </summary>
        public static string lbTitleWarning {
            get {
                return ResourceManager.GetString("lbTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Felicidades!.
        /// </summary>
        public static string lbTitleWinChallenger {
            get {
                return ResourceManager.GetString("lbTitleWinChallenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Felicidades!.
        /// </summary>
        public static string lbTitleWinningGuesser {
            get {
                return ResourceManager.GetString("lbTitleWinningGuesser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string lbUser {
            get {
                return ResourceManager.GetString("lbUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El rival se ha desconectado.
        /// </summary>
        public static string lbUserDisconnected {
            get {
                return ResourceManager.GetString("lbUserDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario y/o correo electrónico ya existen.
        /// </summary>
        public static string lbUserEmailExits {
            get {
                return ResourceManager.GetString("lbUserEmailExits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido.
        /// </summary>
        public static string lbWelcome {
            get {
                return ResourceManager.GetString("lbWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La palabra era:.
        /// </summary>
        public static string lbWordGuess {
            get {
                return ResourceManager.GetString("lbWordGuess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las credenciales ingresadas no corresponden a ningún usuario registrado..
        /// </summary>
        public static string tbMessageErrorCredentials {
            get {
                return ResourceManager.GetString("tbMessageErrorCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay campos vacíos. Complételos o cámbielos para continuar.
        /// </summary>
        public static string tbMessageWarning {
            get {
                return ResourceManager.GetString("tbMessageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        public static string txtRegister {
            get {
                return ResourceManager.GetString("txtRegister", resourceCulture);
            }
        }
    }
}
